import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import {SessionProvider} from "next-auth/react";
import {auth} from "@/auth"
import Navbar from "@/components/layout/Navbar";
import SockerProvider from "@/providers/SocketProvider";
import Container from "@/components/layout/Container";
import { cn } from "@/lib/utils";

const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
      <body
        className={cn(inter.className, 'relative')}
      >
        <SockerProvider>

        
        <main className="flex min-h-screen flex-col bg-secondary">
          <Navbar/>
        <Container>
        {children}
        </Container>
        </main>
        </SockerProvider>
      </body>
    </html>
    </SessionProvider>
  );
}
